---
- name: Common setup (hostname + /etc/hosts)
  hosts: rabbit_nodes
  become: yes

  tasks:

    - name: Set hostname (must match inventory name)
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Update /etc/hosts for RabbitMQ cluster
      blockinfile:
        path: /etc/hosts
        create: yes
        marker: "# {mark} ANSIBLE RABBITMQ CLUSTER"
        block: |
          {% for host in groups['rabbit_nodes'] %}
          {{ hostvars[host].ansible_host | default(hostvars[host].ansible_default_ipv4.address) }} {{ host }}
          {% endfor %}
